// we're going to import state and effect
import {useState, useEffect} from 'react'
import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import AgencyCard from '@components/AgencyCard';
import NavBar from '@components/NavBar';

import { getAgencies } from '@utils/api/agencies';


export default function Home() {
  // we're going to get and load the data
  const [isLoading, setIsLoading] = useState(true)
  const [agencies, setAgencies] = useState() // leave it undefined until we get the data

  // create a loading function
  const loadAgencies = async () => {
    const data = await getAgencies()
    // set the agencies, and handle the lading state.
    setAgencies(data)
    setIsLoading(false)
  }

  // we're going to have an effect that will fetch this on load
  useEffect(()=> {
    loadAgencies()
  }, []) // [] means on mount there

  // handle the loading
  if (isLoading) {
    return "Loading ..."
  }
  // display the agencies if it hits here it'll be defined
  console.log(agencies)


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            Space Agencies
          </Typography>
          <Box
            sx={{
              marginTop: 2,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
            {/* We're going to loop through
            the results of agencies look at the
            agencies in the console to see the
            shape of it. */
            agencies.results.map((agency)=> {
              return <AgencyCard
                key={agency.id}
                // the ? just check if there is an image obj.
                imageUrl={agency.image?.image_url}
                name={agency.name}
                description={agency.description}
                abbreviation={agency.abbrev}
                // we're going to pass in the id of the agency
                id={agency.id}
              />
            })
            }

          </Box>
        </Container>

    </div>
  )
}
